### ISSUE TITLE
Unhandled 'error' event

### ISSUE THREAD

**Issue by system-failure-b8xy** [7coil/svideo#2]
node:events:505
      throw er; // Unhandled 'error' event
      ^

Error: spawn ffprobe.exe ENOENT
    at Process.ChildProcess._handle.onexit (node:internal/child_process:283:19)
    at onErrorNT (node:internal/child_process:478:16)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)
Emitted 'error' event on ChildProcess instance at:
    at Process.ChildProcess._handle.onexit (node:internal/child_process:289:12)
    at onErrorNT (node:internal/child_process:478:16)
    at processTicksAndRejections (node:internal/process/task_queues:83:21) {
  errno: -4058,
  code: 'ENOENT',
  syscall: 'spawn ffprobe.exe',
  path: 'ffprobe.exe',
  spawnargs: [
    '-show_streams',
    '-print_format',
    'json',
    'C:\\MyStuff\\svideo\\fnaf1night1.mp4'
  ]
}

**Comment by system-failure-b8xy** [comment]
Also, sorry for the improper formatting (no indents), I just copied and pasted from CMD.

**Comment by 7coil** [comment]
As I suspected, I'm not actually distributing ffprobe hahaha

**Comment by 7coil** [comment]
As for now, you can put `ffprobe` yourself in your `PATH` to get it temporarily working

**Comment by 7coil** [comment]
```
PS C:\Users\Leondro Lio\Documents\Programming\svideo> svideo -i .\lagrain.webm -o lagtain.sb3
Converting lagrain.webm to lagtain.sb3:
    width     : 480
    height    : 360
    framerate : None - Using video framerate of 15
    format            : jpg
    grid size         : 10 x 10
    compression level : 4
    input video       : C:\Users\Leondro Lio\Documents\Programming\svideo\lagrain.webm
    output project    : lagtain.sb3
    temp folder       : C:\Users\Leondro Lio\Documents\Programming\svideo\temp
    subtitles         : None
    audio interval    : None
    ffmpeg            : C:\Users\Leondro Lio\AppData\Roaming\npm\node_modules\svideo\node_modules\ffmpeg-static\ffmpeg.exe
    ffprobe           : C:\Users\Leondro Lio\AppData\Roaming\npm\node_modules\svideo\node_modules\ffprobe-static\bin\win32\x64\ffprobe.exe
```

The newest version should use the `ffprobe` that's included in `node_modules` - It should be fixed now :)
